### ISSUE TITLE
Directional Graph Edges

### ISSUE THREAD

**Issue by karindaches** [inner-loop/java-neo4j-client#4]
Hi Mark,

When createing a relation in Cypher I can choose to make it directional or not (a-[ ]->(b) vs. a-[ ]-b).
In the Relationship class, this value is not represtented so to know this fact when using GraphStatment queries I have to add it to the created relation properties. I think it should be a class member.

Thank,
Karin Daches

**Comment by mangrish** [comment]
Hi Karin,

You are right. I will update this tomorrow my time. 

::mark

**Comment by karindaches** [comment]
Thanks!

**Comment by mangrish** [comment]
OK I was about to add the change but then i realised it's actually redundant information. The direction is always from the start node to the end node and cannot be any other way.  If i remember correctly, even when you don't add a direction when creating a relationship the underlying neo4j model will create a direction for you.

So when you retrieve a graph you can determine the direction of the relationship between two nodes simply by calling Relationship.getStartNodeId() or Relationship.getEndNodeId(). This is also what is returned in the raw results from the neo4j server.

Let me know if that helps.

**Comment by karindaches** [comment]
Thanks Mark, you are right. Neo4j only supports directed relationship.
For my application I need 'undirected' relations option so I will add it as a property.

**Comment by mangrish** [comment]
cool.. I'll close this issue then. Let me know if you have any other issues :)
